server:
  port: 7003

spring:
  jpa:
    properties:
      hibernate:
        default_schema: dev
  datasource:
    host: craigmiller160.ddns.net
    port: 30019
    username: postgres_root
    password: ${POSTGRES_ROOT_PASSWORD}

logging:
  level:
    io.craigmiller160.authserver: DEBUG
    io.craigmiller160.webutils: DEBUG
